format = '$all$directory$character'

[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ó° … "
style = "blue bold"

[[battery.display]]
threshold = 10
style = "bold red"

# [character]
# vicmd_symbol = '[\[I\]â¯](bold green)'
# success_symbol = "[âœ](bold green) "
# error_symbol = "[âœ—](bold red) "

[git_commit]
tag_disabled = true
only_detached = false
disabled = false
commit_hash_length = 8
tag_symbol = "ğŸ”– "

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 24
truncation_symbol = "..."

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[golang]
format = "via [ğŸğŸ’¨ $version](bold cyan) "

[nodejs]
format = "via [ğŸ¤– $version](bold green) "

[rust]
format = "via [âš™ï¸ $version](red bold)"

[localip]
ssh_only = false
format = "@[$localipv4](bold #0057B8) "
disabled = false

[lua]
format = "via [ğŸŒ• $version](bold blue) "

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold #FFD700"

# ~/.config/starship.toml

[terraform]
format = "via [$symbol $workspace]($style) "
symbol = "ğŸ’ "
style = "bold 105"

[time]
disabled = false
format = '[\[$time\]]($style) '
use_12hr = true
time_format = '%R'
utc_time_offset = '+9'

